# Generated by Django 6.0.1 on 2026-01-27 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actionneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_actionneur', models.CharField(max_length=50)),
                ('etat', models.BooleanField(default=False)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('acquitte_le', models.DateTimeField(blank=True, null=True)),
                ('resolue', models.BooleanField(default=False)),
                ('acquitte_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_acquittees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_capteur', models.CharField(max_length=50)),
                ('unite', models.CharField(blank=True, max_length=20)),
                ('localisation', models.CharField(blank=True, max_length=100)),
                ('seuil_min', models.FloatField(blank=True, null=True)),
                ('seuil_max', models.FloatField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=50)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('actionneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='dashboard.actionneur')),
            ],
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='dashboard.capteur')),
            ],
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
        migrations.AddField(
            model_name='alerte',
            name='capteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='dashboard.capteur'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['capteur'], name='dashboard_a_capteur_5a6447_idx'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['niveau'], name='dashboard_a_niveau_72132c_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquecommande',
            index=models.Index(fields=['actionneur'], name='dashboard_h_actionn_8d1e96_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquecommande',
            index=models.Index(fields=['horodatage'], name='dashboard_h_horodat_b69f13_idx'),
        ),
        migrations.AddIndex(
            model_name='mesure',
            index=models.Index(fields=['capteur'], name='dashboard_m_capteur_6ac6e2_idx'),
        ),
        migrations.AddIndex(
            model_name='mesure',
            index=models.Index(fields=['horodatage'], name='dashboard_m_horodat_98d366_idx'),
        ),
    ]
